// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeglswibjjftovdnfwqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplZ2xzd2liampmdG92ZG5md3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODg4OTksImV4cCI6MjA1ODc2NDg5OX0.JuaS8aienAJYF5kNFdk-a430wsjDccY-LxBOwl4Wcj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);